### ISSUE TITLE
Google calendar

### ISSUE THREAD

**Issue by oganm** [hackseq/hackseq19#10]
I have just made [this](https://calendar.google.com/calendar?cid=N2tvMnMwbmdoY21kcGRtZGdrb3M1aWJoM2dAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ) google calendar. It can be used to ensure everyone (who happens to use google calendar) get reminders when meetings or other important dates are coming up. It is currently empty but could be useful later. You should be able to add it on your own calendars using the link

**Comment by baraaorabi** [comment]
Sounds awesome! Is this created with hackseq@gmail.com account? If not
let's use that instead of personal accounts

**Comment by oganm** [comment]
Well let's use [this](https://calendar.google.com/calendar?cid=cDdkMG91OHY5NjRkNDV1dHQ4c2k2ZDI0YW9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ) link instead then
