### ISSUE TITLE
Sticker Art 19'

### ISSUE THREAD

**Issue by ababaian** [hackseq/hackseq19#14]
Let's be honest, the point of organizing hackseq is to fund our laptop sticker collections. I couldn't help myself last night and cranked out a design I think I like more then the Joy Division one from hs17.

### Pink Floyd - Darkside of the moon
![darkside2](https://user-images.githubusercontent.com/9220907/61584089-d5c95700-ab31-11e9-8e93-af2ec8cf2745.png)

**Comment by alexsweeten** [comment]
Whipped this up a couple months ago.

**Panic! at the Disco**

![panic_disco](https://user-images.githubusercontent.com/7028404/61584262-9252f680-aaf9-11e9-9a8a-f033ae95dc0d.jpg)

**Comment by ababaian** [comment]
I see your panic at the disco and raise you

## Ace of Base - The Sign
![TheSign](https://user-images.githubusercontent.com/9220907/61584655-209b9c80-ab3b-11e9-9d92-4a7c60bb5d8b.png)

(not sure if I like it that much tbh, but it's really funny if you see [the original art beside it](https://upload.wikimedia.org/wikipedia/en/d/d9/AceofBaseTheSignAlbumcover.jpg) )

**Comment by alexsweeten** [comment]
@ababaian Could you send me a vector file of your dark side of the moon design?

**Comment by jenjaelin** [comment]
one of our competitions should be having people design next years' stickers

**Comment by alexsweeten** [comment]
Alternatively: Assign 1 person on each team to design a sticker that represents their project. Can print out their design as a reward.

**Comment by jenjaelin** [comment]
that'd be fun too

**Comment by oganm** [comment]
can we print out their design? do we have sticker making machinery?

**Comment by alexsweeten** [comment]
No, we'd order from a printing company post-hackathon.

**Comment by alexsweeten** [comment]
If anyone has anything else you'd like printed I'm doing a bulk sticker order tomorrow. Let me know!
