### ISSUE TITLE
9th Organizational meeting

### ISSUE THREAD

**Issue by scatcher125** [hackseq/hackseq19#18]
Hey everyone! Next meeting will be on **Thu, Sep 12, 6:00 pm** at the **GSC** (as decided during last meeting).
@emreerhan hope you can confirm once the booking has been made :)

# Minutes

## Team Leads
- email TLs who didn't get a co-lead - Baraa
- connect 2 remaining co-leads/leads - Baraa

## Participant Apps
- got all the projects? 
- make a case for the top 3 
- submit only once, can be edited will get email confirmation
- Timeline: open Friday or Sat., September 27th 1st deadline, push 1 week to October 4th, finalize teams for October 11th
- Baraa to email BioViz with participant application link
- spread sheet to keep track of mail-list - Emre

## Social
- Koerners too expensive, Biercraft for Saturday
- 15% if UBC student makes payment

## Swag
- t-shirts: have bleach party so we don't have to pay for printing (which is the expensive part); Sasha will host
- order extra t-shirts for future years?
- t-shirts for team leads, plus extra to hand out; poll team leads on sizes; order extra S/M/L this time
- long sleeve shirts for organizers, and put something to designate 
- Jen is making stencils + ordering shirts, and figuring out bleaching process

## WIFI
- UN and PW are set, discussed
- ORCA - need to get back with # of teams and specifics

## Logistics
- will have checklist for TLs to keep track of whos attending
- food will be ordered after participant applications are in (Kristen and Jen)
- don't forget to set up slack (~2 week below) - Emre

## Workshops
- Emre to look into organizing github workshop
- Do writing workshops every day again, or just upload workshop materials for this year?  instead have teams review each other's README's to hold teams accountable for making them

## Meetings
- Every week for last 4 weeks before meeting
- doodle poll for day of week that works best: https://doodle.com/poll/gandimgz5w9pp9fp

**Comment by emreerhan** [comment]
Confirmed!

**Comment by jenjaelin** [comment]
Hey! I will definitely be remote next week as I'll be somewhere in Ontario. Access to wifi TBC but I'll let you know :)

**Comment by baraaorabi** [comment]
Cya all @ 6pm!

**Comment by bfjia** [comment]
sorrryyyy forgot about this. Signed up to do something for my grad caucus. I will miss the meeting. Let me know if there's anything i can do to help out!

**Comment by klgray25** [comment]
I will need to skype in tonight! Look me up with my personal email (kristen.leanne252@gmail.com)

**Comment by baraaorabi** [comment]
@Emre do we have Skype setup at GSC? If not I think we can still do VPC

**Comment by emreerhan** [comment]
@baraaorabi I don't believe we have cameras/mics set up at the GSC. We can set up a laptop and hook it up to the projector.

We can do VPC, but it is fairly short notice to be changing location.

**Comment by baraaorabi** [comment]
GSC is just a 10 min walk from GSC and I shouldn't have problem with making
the booking. I guess if we have others beside Kristen who want to Skype we
should switch?

Who else needs to Skype in?

**Comment by jenjaelin** [comment]
I need to skype in

J

**Comment by bfjia** [comment]
> GSC is just a 10 min walk from GSC

Schrödinger's GSC. It's both the GSC and not the GSC until you walk into it.
😂😂

**Comment by baraaorabi** [comment]
Loool. I mean you could walk out for ten min and then come back :-P

**Comment by emreerhan** [comment]
No, that would make it a 20min walk

**Comment by baraaorabi** [comment]
You'd basically walk in an infinitely thin area outside of GSC and
instantaneously walk back in

**Comment by baraaorabi** [comment]
Okie, so let's do VPC!

**Comment by bencardoen** [comment]
I'd need to skype in as well if possible

**Comment by alexsweeten** [comment]
In front of VPC

**Comment by jenjaelin** [comment]
where you all at??

**Comment by klgray25** [comment]
Hey guys - sorry I got caught up doing work! If you are still meeting please call me in

**Comment by smaslova** [comment]
@hackseq/hs19_organizers Don't forget to vote on the doodle poll!  We will have 4 more organizational meetings, one per week leading up to the event.  Vote on the night of the week that works for you.

**Comment by smaslova** [comment]
@hackseq/hs19_organizers based on the doodle poll and the fact that Baraa should probably be at the meetings, we'll do meetings every Thursday at 6pm starting next week and until the hackseq event.  Let me know if there are any objections.
