### ISSUE TITLE
Organizer availability to supervise hackseq

### ISSUE THREAD

**Issue by emreerhan** [hackseq/hackseq19#19]
Hi @hackseq/hs19_organizers,

Can you please copy and paste the following table and checkboxes and comment below to help us determine who will be supervising the actual event on the day of hackseq.

Let me know if you think we should include more information in these comments.

| Date             | Set-up  (8am-9am) | Morning (9am - 12pm)  | Afternoon (12pm - 5pm) |
| ------------|---------------------|------------------------|-------------------------|
| October 18  | [ ] | [ ] | [ ] |
| October 19  | [ ] | [ ] | [ ] |
| October 20 | [ ] | [ ] | [ ] |

I will be either participating or leading a team at hackseq [ ]

**Comment by emreerhan** [comment]
| Date             | Set-up  (8am-9am) | Morning (9am - 12pm)  | Afternoon (12pm - 5pm) |
| ------------|---------------------|------------------------|-------------------------|
| October 18  | [X] | [X] | [] |
| October 19  | [] | [X] | [X] |
| October 20 | [] | [X] | [X] |

I will be either participating or leading a team at hackseq [X]

**Comment by itsDagu** [comment]
Date | Set-up (8am-9am) | Morning (9am - 12pm) | Afternoon (12pm - 5pm)
-- | -- | -- | --
October 18 | [x] | [ ] | [x]
October 19 | [x] | [x] | [x]
October 20 | [x] | [x] | [x]

I will be either participating or leading a team at hackseq [x]

**Comment by klgray25** [comment]
Date | Set-up (8am-9am) | Morning (9am - 12pm) | Afternoon (12pm - 5pm)
-- | -- | -- | --
October 18 | [ ] | [ ] | [ ]
October 19 | [ x] | [ x] | [x ]
October 20 | [ x] | [ x] | [ x]

I will be either participating or leading a team at hackseq []

Note: I can be available later in the afternoon on the Friday, but not from 12-5.

**Comment by smaslova** [comment]
| Date             | Set-up  (8am-9am) | Morning (9am - 12pm)  | Afternoon (12pm - 5pm) |
| ------------|---------------------|------------------------|-------------------------|
| October 18  | [x] | [x] | [x] |
| October 19  | [x] | [x] | [x] |
| October 20 | [x] | [x] | [x] |

I will be either participating or leading a team at hackseq [x]

**Comment by alexsweeten** [comment]
Date | Set-up (8am-9am) | Morning (9am - 12pm) | Afternoon (12pm - 5pm)
-- | -- | -- | --
October 18 | [x] | [x] | [x]
October 19 | [x] | [x] | [x]
October 20 | [x] | [x] | [x]


I will be either participating or leading a team at hackseq [x]

**Comment by kfgibson** [comment]
Date | Set-up  (8am-9am) | Morning (9am - 12pm) | Afternoon (12pm - 5pm)
-- | -- | -- | --
October 18 | [x] | [x] | [x]
October 19 | [ ] | [x] | [x]
October 20 | [ ] | [x] | [x]

I will be either participating or leading a team at hackseq [x]

**Comment by scatcher125** [comment]
I won't be there in person during Hackseq unfortunately, but I will likely be a remote participant.

DateSet-up (8am-9am)Morning (9am - 12pm)Afternoon (12pm - 5pm)October 18[ ][ ][ ]October 19[ ][ ][ ]October 20[ ][ ][ ]

I will be either participating or leading a team at hackseq [ x]

**Comment by scatcher125** [comment]
I won't be able to be present in person unfortunately, but I do plan to participate remotely.

**Comment by baraaorabi** [comment]
| Date             | Set-up  (8am-9am) | Morning (9am - 12pm)  | Afternoon (12pm - 5pm) |
| ------------|---------------------|------------------------|-------------------------|
| October 18  | [x] | [x] | [x] |
| October 19  | [x] | [x] | [x] |
| October 20 | [x] | [x] | [x] |

I will be either participating or leading a team at hackseq [ ]

**Comment by jenjaelin** [comment]
| Date             | Set-up  (8am-9am) | Morning (9am - 12pm)  | Afternoon (12pm - 5pm) |
| ------------|---------------------|------------------------|-------------------------|
| October 18  | [ x] | [ x] | [ ] |
| October 19  | [ x] | [x ] | [x ] |
| October 20 | [x ] | [x ] | [x ] |

I will be either participating or leading a team at hackseq [ ]

**Comment by bfjia** [comment]
Date | Set-up  (8am-9am) | Morning (9am - 12pm) | Afternoon (12pm - 5pm)
-- | -- | -- | --
October 18 | [x ] | [x ] | [x ]
October 19 | [x ] | [x ] | [x ]
October 20 | [x ] | [x ] | [x ]

I will be either participating or leading a team at hackseq [ x]

**Comment by arisgrout** [comment]
Date | Set-up (8am-9am) | Morning (9am - 12pm) | Afternoon (12pm - 5pm)
-- | -- | -- | --
October 18 | [x ] | [x ] | [x ]
October 19 | [x ] | [x ] | [x ]
October 20 | [x ] | [x ] | [x ]

I will be either participating or leading a team at hackseq [ x ]
