### ISSUE TITLE
0th Organizational Meeting

### ISSUE THREAD

**Issue by emreerhan** [hackseq/hackseq19#2]
Hello hackseq19 organizers,

Please vote [at this doodle poll](https://doodle.com/poll/x3m5rau6yg9iz9x5) for your availability to meet. The objective of the meeting will be to organize ourselves into a working group, divide tasks and establish a rough timeline for when/what needs to be accomplished.

Please get in touch with motivated and competent individuals and refer them to this issue if they would like to show up. Everyone is welcome to help out as much or as little as they would like, but we'll likely settle into ~8-12 person group as being solely responsible for an aspect of the event.

### [Poll Link](https://doodle.com/poll/x3m5rau6yg9iz9x5)

(Assign someone to take meeting minutes)

## Agenda Items (feel free to add)
- Hello + Welcome

### hackseq18
- Summary from previous committee
- Budget and finances

### hackseq19
- New organizing committee
- - Positions
- - Additional recruitment?

- Logistics
- - Event Date / Format
- - Location Choice
- - Organizational Time-table
- - Projected Budget

- Website
- - update frontpage
- - hackseq19 registration / splash page

- Partnerships
- - ECOSCOPE
- - Medical Genetics
- - GrassPods
- - SCWIST

- Tasks for Second Organizational Meeting

### Attendance

- 6 organizers attended in-person
  - Emre
  - Kristen
  - Sasha
  - Justin
  - Alex
  - Baraa
  - Artem (not organizing)

- 3 organizers teleconferenced in
  - Reva
  - David
  - Noushin

### Organizer roles

We briefly discussed what we may be interested in

- Emre: tech lead, maybe sponsorship too
- Alex: website
- Justin: team leaders?
- Kirsten: logistics?
- Sasha: Participant applications/sorting
- Baraa: Email and more
- David: recruitment. team leaders and participants. 
- Noushin: social media
- Reva: secretary

For those who are unsure, check out the hackseq18 wiki

### Misc

- Add an incentive for sponsors. Let them walk around hackathon and collect resumes if they wish.
- Last year we did not have enough teams. This year, try to get many teams.
- Major league hacking?

### Action points

- @emreerhan will contact Dr. Steve Hallam to talk about ECOSCOPE sponsor
- everyone will look up potential conferences or events to line up hackseq19 with

**Comment by NoushinN** [comment]
Would joining online be possible? I don't want to impose bad practice as far as attendance goes for these meetings but I am on the Island! If team sees fit, I can take on some activities remotely :)

**Comment by ababaian** [comment]
What's the plan @emreerhan?

**Comment by emreerhan** [comment]
Hi everyone, let's meet February 21 at 6:00pm. I will book a room at the GSC or BCCRC and let you know where we're meeting this week.

**Comment by emreerhan** [comment]
@NoushinN I don't want to speak for the rest of the group, but I personally think it will be difficult to video call you into a meeting with 8-10 people. If you think it can work, we can give it a shot and see if we want to allow the remote option for future meetings.

Regardless, I think you can certainly take on some responsibilities remotely!

**Comment by NoushinN** [comment]
Hi @emreerhan, sounds good. I can also keep updated based on meeting notes and work on things that get delegated to me remotely. Will send the call specifics before the meeting on 21st.

**Comment by emreerhan** [comment]
We will meet in the Smith Rm. at the Genome Sciences Centre at 570 W 7th Ave. Let's meet in the lobby at 5:55pm, and I'll take us all up to the room.

**Comment by baraaorabi** [comment]
This is a reminder that we are meeting this Thurs, in two days.

**Comment by NoushinN** [comment]
I can be reached through the following:

Join by Phone 
Local - Vancouver: +1 (604) 398-9304,, 5692673#
Toll-Free: +1 (888) 952-9304,, 5692673#
Local - Victoria: +1 (250) 952-9304,, 5692673#
Find a local number 

Conference ID: 5692673 

IF I don't hear back, I will wait for meeting updates

**Comment by baraaorabi** [comment]
Cya all at 5:55pm today!

**Comment by scatcher125** [comment]
Is it too late to join the meeting? I can be present digitally for today's meeting at 6 pm :)

**Comment by emreerhan** [comment]
@scatcher125 If we can get you on the same platform @NoushinN is on, then yes you may. I'm not sure how this conference call works, but you may be able to just call the number and enter the conference ID. @NoushinN can you confirm if you see this on time?

**Comment by itsDagu** [comment]
Same, I will be unable to join the meeting physically, but I will be present online at 6pm.

**Comment by scatcher125** [comment]
> @scatcher125 If we can get you on the same platform @NoushinN is on, then yes you may. I'm not sure how this conference call works, but you may be able to just call the number and enter the conference ID. @NoushinN can you confirm if you see this on time?

Thankyou! I'll try calling at 6:00

**Comment by emreerhan** [comment]
Fyi we haven't started yet. Will keep you updated.

**Comment by emreerhan** [comment]
We are going upstairs. If you arrive later please message here or text/call me at 604 779 6549

**Comment by NoushinN** [comment]
Hi @emreerhan there are 3 of us on the line so if someone can connect at GSC we can all hear you
Local - Vancouver: +1 (604) 398-9304,, 5692673#
Toll-Free: +1 (888) 952-9304,, 5692673#
Local - Victoria: +1 (250) 952-9304,, 5692673#

**Comment by arisgrout** [comment]
Hi All, are minutes available from Thursday? I wasn't able to attend. Hope it went well, cheers!

**Comment by emreerhan** [comment]
Minutes are up

Hey @arisgrout! Check out the [new meeting issue](https://github.com/hackseq/hackseq19/issues/3) and fill out the doodle poll. Make sure you're watching the hackseq19 repo to keep updated with all the conversations!
