### ISSUE TITLE
10th Organizational Meeting - Tues. Sept. 24th 6pm

### ISSUE THREAD

**Issue by smaslova** [hackseq/hackseq19#20]
Hey everyone! Next meeting will be on Tue, Sep 24, 6:00 pm at the VPC.

@baraaorabi could you make a room booking at the VPC?

# Agenda
- ordering shirts
- hackseq deliverable
- participant application
  - extension
  - second wave of advertising?
  - extra dates in form?
  - who will divide people into teams
- Add schedule to website

# Minutes

## Participant applications 
- [ ] extend to next Thursday
- [ ] Ogan, Sasha and Jenny to do participant apps on thursday or after

## Deliverables
- [ ] Baraa - to tell TLs that the task list per day (deliverable) and who is responsible
- [ ] Kristen as speed dating Tzar - trios

## Misc
- [ ] Emre - talk to Orca
- [ ] Justin to email about payment
- [ ] Jenny to make task list for days of
- [ ] Emre - Github and Slack set up
- [ ] Alex to put github/website up on site if wanted
- [ ] RSVPs send out on monday the 7th

## swag
- [ ] order shirts 20/30/20/10
- [ ] Baraa to mail list TLs for shirt sizes
- [ ] Oct 5th or 6th for clothing deco party
- [ ] Alex to order stickers - if have ideas, do them for tomorrow

**Comment by baraaorabi** [comment]
Done!

**Comment by arisgrout** [comment]
@smaslova @baraaorabi was there a doodle for this that I missed? I thought there would be a doodle for regular meetings moving forward :/ As mentioned during last meeting, I can't make Thursdays Sept. 26th onwards.

**Comment by emreerhan** [comment]
@smaslova reminded me today that we have VanBUG on Thursday. @baraaorabi is that still next Thursday? If it is, we should move the date.

**Comment by baraaorabi** [comment]
I guess since we have a majority for Tues on the Doodle let's do that instead. I have a class at UBC till 5, but that should be enough time to get back to VPC

**Comment by scatcher125** [comment]
I have class until 6:30 pst on both tue & thu, so I can join once it ends. I forgot to account for the time difference in the poll.

**Comment by bencardoen** [comment]
So just to make sure, no meeting today but Tue instead?

**Comment by baraaorabi** [comment]
The meeting was gonna be next Thurs. I guess now it will be two days earlier instead.

**Comment by baraaorabi** [comment]
I just made the booking for tomorrow at VPC. Cya all tomorrow at 6!

**Comment by klgray25** [comment]
Sorry, but I will likely have to call in again

**Comment by bfjia** [comment]
I shall Skype in to today's meeting too

**Comment by scatcher125** [comment]
I can skype in! Managed to completely confuse myself about timings. 6 pm is 9 pm for me, not 3 pm smh :/

**Comment by klgray25** [comment]
I can actually come in person now

**Comment by baraaorabi** [comment]
Sweet! Cya all in 3 hours

**Comment by arisgrout** [comment]
I'll be skyping probably a few late sorry

**Comment by kfgibson** [comment]
I am going to try to skype in, but I might not get home in time!

**Comment by baraaorabi** [comment]
I sent out new email with the deadline extension.

@emreerhan can u get on the Slack & git pages?

**Comment by emreerhan** [comment]
hackseq19 slack: https://join.slack.com/t/hackseq19/shared_invite/enQtNzc3MDAzOTczODMxLWZjZTA0ZGNjNDRkZDI4YWEyYTlkNjg2MGM1ZjQ5NTZhMTYxMjRlN2U4MTM0YzJjOGM5YjZhNzdmYWU4YmQ2YjM

I'll do github pages later

**Comment by baraaorabi** [comment]
Ok I just sent an email to the teamleads with the slack link!

**Comment by scatcher125** [comment]
Updating the participant application form with the new deadline - Thu, 3rd Sep.
