### ISSUE TITLE
11th Organizational meeting - Tue, 1-Oct, 6 pm

### ISSUE THREAD

**Issue by scatcher125** [hackseq/hackseq19#22]
Next meeting will be Tuesday, 11-Oct-2019, 6:00 pm at VPC!

# Agenda
- Participant application sorting time/location
  - priorities? 
- Shirt #'s, deco party
- Banner?
- people flying in priority
- Schedule/[To Do list](https://docs.google.com/spreadsheets/d/1WCH1sH033biQLzEx5FOq0BMQnSvGELoYuiMKNkeiDrU/edit?usp=sharing)

# Minutes

## Participation
- if reasonable give remote what they want
- if leads have members they want on their team
- 3 days over less
- small group for a project, if even then start with adding them all first
- preferred team size if possible
- avg. 6.5 per team
- email for acceptance to include RSVP
  - Aris to ask Baraa how it's done
- figure out mutual day for it @ BCCHRI w Jenny, Sasha and Ogan
  - send list to Aris when done

## Shirts 
- printing on Saturday 2pm at BC Chlidren's

## Competitions
- Haiku
- Science/bio/CS memes
- "Things heard at hackseq'19" -
- hand drawn doodles
- VIP

## Misc
- storage - where to keep?
  - Sharon?
  - Emre to ask around
  - Jenny to send out email tonight - shirts, members on team from own lab
- what was the algorithm for voting?
- Banner?
- Sasha to ask about extra chairs if needed (?)
- Emre to balance out computing resources
- Emre to make email to people who are travelling in from away

**Comment by baraaorabi** [comment]
Hey @hackseq/hs19_organizers! Something came and I won't be able to make for tomorrow's meeting. Can we either have:
- @emreerhan book a room at GSC instead? or
- move the meeting to either Wed or Thu?

**Comment by oganm** [comment]
We also have free rooms at UBC

**Comment by emreerhan** [comment]
I can book the GSC

**Comment by bencardoen** [comment]
I can't make it, I have a paper rebuttal deadline, sorry.

**Comment by baraaorabi** [comment]
Can we have a quick show of hands for who can make it in person to GSC today and who prefers Wed or Thurs? If we don't have clear result we should stick with the original time of today but at GSC.

**Comment by itsDagu** [comment]
I won’t be there in person but will be Skyping in!



________________________________

**Comment by baraaorabi** [comment]
I don't think we can set up Skype at GSC

**Comment by smaslova** [comment]
I'm not feeling well so I don't think I'll make it today.

**Comment by emreerhan** [comment]
Yes we can't set up Skype at the GSC. I'll be there

**Comment by klgray25** [comment]
I can be there today. I don't think I can do Thursday this week anymore.

**Comment by jenjaelin** [comment]
I can do either :)

**Comment by arisgrout** [comment]
I can do today or Wednesday

**Comment by baraaorabi** [comment]
Ok I guess let's just stick with today at GSC

**Comment by emreerhan** [comment]
Hey @hackseq/hs19_organizers we'll be at the GSC today at 6pm. Unfortunately we don't have skype capability here, so no remote participants today. Please post updates below if you have any and are unable to attend.

**Comment by bfjia** [comment]
unable to attend :(

**Comment by jenjaelin** [comment]
@emreerhan is that just where we used to meet last year?

**Comment by emreerhan** [comment]
No, it's at the Echelon building.

570 W 7th Ave, Vancouver, BC V5Z 4S6
I'll be waiting at the door at 6pm. If you arrive late, post on this thread and I'll come down to get you.

**Comment by emreerhan** [comment]
Were upstairs now. Message here (or FB or something) if you arrive late

**Comment by oganm** [comment]
Arrived late!
