### ISSUE TITLE
Organizer Photos

### ISSUE THREAD

**Issue by alexsweeten** [hackseq/hackseq19#5]
Hey everyone,

I'd like to update our list of organizers on the website. If you could submit a photo of yourself, along with what you're currently doing (undergrad in BIO/STATS at UBC, technician at Genome Science Centre, etc.) that would be great :)

**Comment by emreerhan** [comment]
![emre_headshot](https://user-images.githubusercontent.com/10843112/55584119-5d509e80-56d8-11e9-8804-300457527ba4.jpg)
Name: Emre Erhan
Affiliation: Bioinformatics MSc student at UBC

**Comment by baraaorabi** [comment]
Baraa Orabi
PhD Student at UBC Computer Science and Vancouver Prostate Centre

![baraa-orabi](https://user-images.githubusercontent.com/6283321/55584148-6c375100-56d8-11e9-8fff-64ba28989090.jpg)

**Comment by bfjia** [comment]
Justin Jia
Ph.D Candidate | Brinkman Lab, Molecular Biology and Biochemistry, SFU

can you use the photo from last year? I don't have it readily available

**Comment by NoushinN** [comment]
Noushin Nabavi
Canadian Science Policy Fellow @ BCGov
- would also appreciate if you use my photo from last year

**Comment by bencardoen** [comment]
Ben Cardoen
PhD Student Computing Science, Medical Image Analysis Lab, SFU / Life Sciences Centre, UBC
![photo](https://user-images.githubusercontent.com/26388277/55588520-d7862080-56e2-11e9-9400-05e94fa04f27.jpeg)

**Comment by oganm** [comment]
Bioinformatics PhD student, Pavlidis Lab, UBC

![6352379 (2)](https://user-images.githubusercontent.com/6352379/55589477-27fe7d80-56e5-11e9-8a1d-b4b0160b8ee8.jpeg)

**Comment by jenjaelin** [comment]
Jennifer Lin
Medical Genetics MSc. Candidate, Carleton Lab

Same photo as last year please :)

**Comment by itsDagu** [comment]
David Guo
Undergrad in Biostatistics at UBC

<img src="https://user-images.githubusercontent.com/21967618/55593453-c5ab7a00-56f0-11e9-8302-1ae0624659c2.jpg" width="350">

**Comment by alexsweeten** [comment]
Thanks everyone! 

If you've organized before and haven't commented then I'll reuse last years photos. If you're new then I'll stalk your LinkedIn/Facebook ;)

**Comment by saberhq** [comment]
@SweetiePi Sorry for the late reply. I missed the chance to attend our first two meetings and I am not sure you guys still accept me as an organizer or not. :D However, here is my profile pic. I am planning to attend the rest of meetings hopefully.

Bioinformatics PhD student at UBC / BC Cancer Agency

![Saber_HafezQorani](https://user-images.githubusercontent.com/13000878/55826366-b8a9d480-5abc-11e9-8a4e-7561bd24fbcd.jpg)
